//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenBaseAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int SalesID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string SalesPerson { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
